export const construction = [
  { type: 'Massivhaus' },
  { type: 'Fertighaus' },
  { type: 'Fachwerkhauser' },
  { type: 'Blockhäuser' },
  { type: 'Holzhaus' },
];

export const tags = [
  { tag: 'Neubauprojekt' },
  { tag: 'Balkon' },
  { tag: 'Terrasse' },
  { tag: 'Garten' },
  { tag: 'Parkplatz' },
  { tag: 'Teilmöbliert' },
  { tag: 'Möbliert' }

];

export const estateTypes = [
  { type: '1-Zimmer' },
  { type: '2-Zimmer' },
  { type: '3-Zimmer' },
  { type: '4-Zimmer' },
  { type: '5+ Zimmer' },
  { type: 'Maisonette' },
  { type: 'Büro' },
  { type: 'Häuser' },
  { type: 'Villen' },
  { type: 'Einzelhandel' },
  { type: 'Lokale' },
  { type: 'Industrie' },
  { type: 'Garagen' },
  { type: 'Gewerbliche Grundstücke' },
  { type: 'Grundstücke' },
  { type: 'Land- und Forstwirtschaft' },
  { type: 'Hotels und Pensionen' }
];

export const cities = () => {
  return [
    { name: 'Wien', searchValue: 'WN' },
    { name: 'Vorarlberg', searchValue: 'VRLB' },
    { name: 'Tirol', searchValue: 'TL' },
    { name: 'Steiermark', searchValue: 'STM' },
    { name: 'Salzburg', searchValue: 'SLB' },
    { name: 'Oberösterreich', searchValue: 'OBOST' },
    { name: 'Niederösterreich', searchValue: 'NDOST' },
    { name: 'Kärnten', searchValue: 'KRTN' },
    { name: 'Burgenland', searchValue: 'BRGL' }
  ];
};

export const townOptions = {
  WN: [
    { name: 'Wien 1.,Innere Stadt' },
    { name: 'Wien 2.,Leopoldstadt' },
    { name: 'Wien 3.,Landstraße' },
    { name: 'Wien 4.,Wieden' },
    { name: 'Wien 5.,Margareten' },
    { name: 'Wien 6.,Mariahilf' },
    { name: 'Wien 7.,Neubau' },
    { name: 'Wien 8.,Josefstadt' },
    { name: 'Wien 9.,Alsergrund' },
    { name: 'Wien 10.,Favoriten' },
    { name: 'Wien 11.,Simmering' },
    { name: 'Wien 12.,Meidling' },
    { name: 'Wien 13.,Hietzing' },
    { name: 'Wien 14.,Penzing' },
    { name: 'Wien 15.,Rudolfsheim-Fünfhaus' },
    { name: 'Wien 16.,Ottakring' },
    { name: 'Wien 17.,Hernals' },
    { name: 'Wien 18.,Währing' },
    { name: 'Wien 19.,Döbling' },
    { name: 'Wien 20.,Brigittenau' },
    { name: 'Wien 21.,Floridsdorf' },
    { name: 'Wien 22.,Donaustadt' },
    { name: 'Wien 23.,Liesing' }
  ],

  VRLB: [
    { name: 'Alberschwende' },
    { name: 'Altach' },
    { name: 'Andelsbuch' },
    { name: 'Au' },
    { name: 'Bartholomäberg' },
    { name: 'Bezau' },
    { name: 'Bildstein' },
    { name: 'Bizau' },
    { name: 'Blons' },
    { name: 'Bludenz 	Stadt: Bezirk Bludenz' },
    { name: 'Bludesch' },
    { name: 'Brand' },
    { name: 'Bregenz 	Stadt: Bezirk Bregenz' },
    { name: 'Buch' },
    { name: 'Bürs' },
    { name: 'Bürserberg' },
    { name: 'Dalaas 	' },
    { name: 'Damüls 	' },
    { name: 'Doren 	' },
    { name: 'Dornbirn 	Stadt: Bezirk Dornbirn' },
    { name: 'Düns 	' },
    { name: 'Dünserberg 	' },
    { name: 'Egg 	' },
    { name: 'Eichenberg 	' },
    { name: 'Feldkirch 	Stadt: Bezirk Feldkirch' },
    { name: 'Fontanella 	' },
    { name: 'Frastanz 	' },
    { name: 'Fraxern 	' },
    { name: 'Fußach 	' },
    { name: 'Gaißau 	' },
    { name: 'Gaschurn 	' },
    { name: 'Göfis 	' },
    { name: 'Götzis 	' },
    { name: 'Hard ' },
    { name: 'Hittisau 	' },
    { name: 'Höchst 	' },
    { name: 'Hohenems ' },
    { name: 'Hohenweiler 	' },
    { name: 'Hörbranz 	' },
    { name: 'Innerbraz 	' },
    { name: 'Kennelbach 	' },
    { name: 'Klaus 	' },
    { name: 'Klösterle 	' },
    { name: 'Koblach 	' },
    { name: 'Krumbach 	' },
    { name: 'Langen bei Bregenz 	' },
    { name: 'Langenegg 	' },
    { name: 'Laterns 	' },
    { name: 'Lauterach 	' },
    { name: 'Lech 	' },
    { name: 'Lingenau 	' },
    { name: 'Lochau 	' },
    { name: 'Lorüns 	' },
    { name: 'Ludesch 	' },
    { name: 'Lustenau 	' },
    { name: 'Mäder 	' },
    { name: 'Meiningen 	' },
    { name: 'Mellau 	' },
    { name: 'Mittelberg 	' },
    { name: 'Möggers 	' },
    { name: 'Nenzing 	' },
    { name: 'Nüziders 	' },
    { name: 'Raggal 	' },
    { name: 'Rankweil 	Marktgemeinde: Bezirk Feldkirch' },
    { name: 'Reuthe 	' },
    { name: 'Riefensberg 	' },
    { name: 'Röns 	' },
    { name: 'Röthis 	' },
    { name: 'Satteins 	' },
    { name: 'Schlins 	' },
    { name: 'Schnepfau 	' },
    { name: 'Schnifis 	' },
    { name: 'Schoppernau 	' },
    { name: 'Schröcken 	' },
    { name: 'Schruns 	Marktgemeinde: Bezirk Bludenz' },
    { name: 'Schwarzach 	' },
    { name: 'Schwarzenberg 	' },
    { name: 'Sibratsgfäll 	' },
    { name: 'Silbertal 	' },
    { name: 'Sonntag 	' },
    { name: 'St. Anton im Montafon 	' },
    { name: 'St. Gallenkirch 	' },
    { name: 'St. Gerold 	' },
    { name: 'Stallehr 	' },
    { name: 'Sulz 	' },
    { name: 'Sulzberg 	' },
    { name: 'Thüringen 	' },
    { name: 'Thüringerberg 	' },
    { name: 'Tschagguns 	' },
    { name: 'Übersaxen 	' },
    { name: 'Vandans 	' },
    { name: 'Viktorsberg 	' },
    { name: 'Warth 	' },
    { name: 'Weiler 	' },
    { name: 'Wolfurt 	' },
    { name: 'Zwischenwasser ' }
  ],

  TL: [
    { name: 'Abfaltersbach ezirk' },
    { name: 'Absam' },
    { name: 'Achenkirch' },
    { name: 'Ainet' },
    { name: 'Aldrans' },
    { name: 'Alpbach' },
    { name: 'Amlach' },
    { name: 'Ampass' },
    { name: 'Angath' },
    { name: 'Angerberg' },
    { name: 'Anras' },
    { name: 'Arzl im Pitztal' },
    { name: 'Aschau im Zillertal' },
    { name: 'Assling' },
    { name: 'Aurach bei Kitzbühel' },
    { name: 'Außervillgraten' },
    { name: 'Axams' },
    { name: 'Bach' },
    { name: 'Bad Häring' },
    { name: 'Baumkirchen' },
    { name: 'Berwang' },
    { name: 'Biberwier' },
    { name: 'Bichlbach' },
    { name: 'Birgitz' },
    { name: 'Brandberg' },
    { name: 'Brandenberg' },
    { name: 'Breitenbach am Inn' },
    { name: 'Breitenwang' },
    { name: 'Brixen im Thale' },
    { name: 'Brixlegg' },
    { name: 'Bruck am Ziller' },
    { name: 'Buch in Tirol' },
    { name: 'Dölsach' },
    { name: 'Ebbs' },
    { name: 'Eben am Achensee' },
    { name: 'Ehenbichl' },
    { name: 'Ehrwald' },
    { name: 'Elbigenalp' },
    { name: 'Ellbögen' },
    { name: 'Ellmau' },
    { name: 'Elmen' },
    { name: 'Erl' },
    { name: 'Faggen' },
    { name: 'Fendels' },
    { name: 'Fieberbrunn' },
    { name: 'Finkenberg' },
    { name: 'Fiss' },
    { name: 'Flaurling' },
    { name: 'Fließ' },
    { name: 'Flirsch' },
    { name: 'Forchach' },
    { name: 'Fritzens' },
    { name: 'Fügen' },
    { name: 'Fügenberg' },
    { name: 'Fulpmes' },
    { name: 'Gaimberg' },
    { name: 'Gallzein' },
    { name: 'Galtür' },
    { name: 'Gerlos' },
    { name: 'Gerlosberg' },
    { name: 'Gnadenwald' },
    { name: 'Going am Wilden Kaiser' },
    { name: 'Götzens' },
    { name: 'Gramais' },
    { name: 'Grän' },
    { name: 'Gries am Brenner' },
    { name: 'Gries im Sellrain' },
    { name: 'Grins' },
    { name: 'Grinzens' },
    { name: 'Gschnitz' },
    { name: 'Haiming' },
    { name: 'Hainzenberg' },
    { name: 'Hall in Tirol-Stadt Bezirk Innsbruck-Land' },
    { name: 'Hart im Zillertal' },
    { name: 'Häselgehr' },
    { name: 'Hatting' },
    { name: 'Heinfels' },
    { name: 'Heiterwang' },
    { name: 'Hinterhornbach' },
    { name: 'Hippach' },
    { name: 'Hochfilzen' },
    { name: 'Höfen' },
    { name: 'Holzgau' },
    { name: 'Hopfgarten im Brixental' },
    { name: 'Hopfgarten in Defereggen' },
    { name: 'Imst-Stadt Bezirk Imst' },
    { name: 'Imsterberg' },
    { name: 'Innervillgraten' },
    { name: 'Innsbruck -Statutarstadt Bezirk Innsbruck-Stadt' },
    { name: 'Inzing' },
    { name: 'Ischgl' },
    { name: 'Iselsberg-Stronach' },
    { name: 'Itter' },
    { name: 'Jenbach' },
    { name: 'Jerzens' },
    { name: 'Jochberg' },
    { name: 'Jungholz' },
    { name: 'Kaisers' },
    { name: 'Kals am Großglockner' },
    { name: 'Kaltenbach' },
    { name: 'Kappl' },
    { name: 'Karres' },
    { name: 'Karrösten' },
    { name: 'Kartitsch' },
    { name: 'Kaunerberg' },
    { name: 'Kaunertal' },
    { name: 'Kauns' },
    { name: 'Kematen in Tirol' },
    { name: 'Kirchberg in Tirol' },
    { name: 'Kirchbichl' },
    { name: 'Kirchdorf in Tirol' },
    { name: 'Kitzbühel-Stadt Bezirk Kitzbühel' },
    { name: 'Kolsass' },
    { name: 'Kolsassberg' },
    { name: 'Kössen' },
    { name: 'Kramsach' },
    { name: 'Kufstein-Stadt Bezirk Kufstein' },
    { name: 'Kundl' },
    { name: 'Ladis' },
    { name: 'Landeck-Stadt Bezirk Landeck' },
    { name: 'Längenfeld' },
    { name: 'Langkampfen' },
    { name: 'Lans' },
    { name: 'Lavant' },
    { name: 'Lechaschau' },
    { name: 'Leisach' },
    { name: 'Lermoos' },
    { name: 'Leutasch' },
    { name: 'Lienz-Stadt Bezirk Lienz' },
    { name: 'Mariastein' },
    { name: 'Matrei am Brenner' },
    { name: 'Matrei in Osttirol' },
    { name: 'Mayrhofen' },
    { name: 'Mieders' },
    { name: 'Mieming' },
    { name: 'Mils' },
    { name: 'Mils bei Imst' },
    { name: 'Mötz' },
    { name: 'Münster' },
    { name: 'Musau' },
    { name: 'Mutters' },
    { name: 'Namlos' },
    { name: 'Nassereith' },
    { name: 'Natters' },
    { name: 'Nauders' },
    { name: 'Navis' },
    { name: 'Nesselwängle' },
    { name: 'Neustift im Stubaital' },
    { name: 'Niederndorf' },
    { name: 'Niederndorferberg' },
    { name: 'Nikolsdorf' },
    { name: 'Nußdorf-Debant' },
    { name: 'Oberhofen im Inntal' },
    { name: 'Oberlienz' },
    { name: 'Obernberg am Brenner' },
    { name: 'Oberndorf in Tirol' },
    { name: 'Oberperfuss' },
    { name: 'Obertilliach' },
    { name: 'Obsteig' },
    { name: 'Oetz' },
    { name: 'Patsch' },
    { name: 'Pettnau' },
    { name: 'Pettneu am Arlberg' },
    { name: 'Pfaffenhofen' },
    { name: 'Pfafflar' },
    { name: 'Pflach' },
    { name: 'Pfunds' },
    { name: 'Pians' },
    { name: 'Pill' },
    { name: 'Pinswang' },
    { name: 'Polling in Tirol' },
    { name: 'Prägraten am Großvenediger' },
    { name: 'Prutz' },
    { name: 'Radfeld' },
    { name: 'Ramsau im Zillertal' },
    { name: 'Ranggen' },
    { name: 'Rattenberg-Stadt Bezirk Kufstein' },
    { name: 'Reith bei Kitzbühel' },
    { name: 'Reith bei Seefeld' },
    { name: 'Reith im Alpbachtal' },
    { name: 'Rettenschöss' },
    { name: 'Reutte' },
    { name: 'Ried im Oberinntal' },
    { name: 'Ried im Zillertal' },
    { name: 'Rietz' },
    { name: 'Rinn' },
    { name: 'Rohrberg' },
    { name: 'Roppen' },
    { name: 'Rum' },
    { name: 'Sautens' },
    { name: 'Scharnitz' },
    { name: 'Schattwald' },
    { name: 'Scheffau am Wilden Kaiser' },
    { name: 'Schlaiten' },
    { name: 'Schlitters' },
    { name: 'Schmirn' },
    { name: 'Schönberg im Stubaital' },
    { name: 'Schönwies' },
    { name: 'Schwaz-Stadt Bezirk Schwaz' },
    { name: 'Schwendau' },
    { name: 'Schwendt' },
    { name: 'Schwoich' },
    { name: 'See' },
    { name: 'Seefeld in Tirol' },
    { name: 'Sellrain' },
    { name: 'Serfaus' },
    { name: 'Sillian' },
    { name: 'Silz' },
    { name: 'Sistrans' },
    { name: 'Sölden' },
    { name: 'Söll' },
    { name: 'Spiss' },
    { name: 'St. Anton am Arlberg' },
    { name: 'St. Jakob in Defereggen' },
    { name: 'St. Jakob in Haus' },
    { name: 'St. Johann im Walde' },
    { name: 'St. Johann in Tirol' },
    { name: 'St. Leonhard im Pitztal' },
    { name: 'St. Sigmund im Sellrain' },
    { name: 'St. Ulrich am Pillersee' },
    { name: 'St. Veit in Defereggen' },
    { name: 'Stams' },
    { name: 'Stans' },
    { name: 'Stanz bei Landeck' },
    { name: 'Stanzach' },
    { name: 'Steeg' },
    { name: 'Steinach am Brenner' },
    { name: 'Steinberg am Rofan' },
    { name: 'Strass im Zillertal' },
    { name: 'Strassen' },
    { name: 'Strengen' },
    { name: 'Stumm' },
    { name: 'Stummerberg' },
    { name: 'Tannheim' },
    { name: 'Tarrenz' },
    { name: 'Telfes im Stubai' },
    { name: 'Telfs' },
    { name: 'Terfens' },
    { name: 'Thaur' },
    { name: 'Thiersee' },
    { name: 'Thurn' },
    { name: 'Tobadill' },
    { name: 'Tösens' },
    { name: 'Trins' },
    { name: 'Tristach' },
    { name: 'Tulfes' },
    { name: 'Tux' },
    { name: 'Uderns' },
    { name: 'Umhausen' },
    { name: 'UnterperfusS' },
    { name: 'Untertilliach' },
    { name: 'Vals' },
    { name: 'Vils-Stadt Bezirk Reutte' },
    { name: 'Virgen' },
    { name: 'Volders' },
    { name: 'Völs' },
    { name: 'Vomp' },
    { name: 'Vorderhornbach' },
    { name: 'Waidring' },
    { name: 'Walchsee' },
    { name: 'Wängle' },
    { name: 'Wattenberg' },
    { name: 'Wattens' },
    { name: 'Weer' },
    { name: 'Weerberg' },
    { name: 'Weißenbach am Lech' },
    { name: 'Wenns' },
    { name: 'Westendorf' },
    { name: 'Wiesing' },
    { name: 'Wildermieming' },
    { name: 'Wildschönau' },
    { name: 'Wörgl-Stadt Bezirk Kufstein' },
    { name: 'Zams' },
    { name: 'Zell am Ziller' },
    { name: 'Zellberg' },
    { name: 'Zirl' },
    { name: 'Zöblen' }
  ],

  STM: [
    { name: 'Adomnt' },
    { name: 'Aflenz' },
    { name: 'Aich ' },
    { name: 'Aigen im Ennstal ' },
    { name: 'Albersdorf-Prebuch ' },
    { name: 'Allerheiligen bei Wildon ' },
    { name: 'Altaussee ' },
    { name: 'Altenmarkt bei Sankt Gallen' },
    { name: 'Anger' },
    { name: 'Ardning ' },
    { name: 'Arnfels' },
    { name: 'Bad Aussee-Stadt Bezirk Liezen' },
    { name: 'Bad Blumau ' },
    { name: 'Bad Gleichenberg ' },
    { name: 'Bad Loipersdorf ' },
    { name: 'Bad Mitterndorf' },
    { name: 'Bad Radkersburg-Stadt Bezirk Südoststeiermark' },
    { name: 'Bad Schwanberg' },
    { name: 'Bad Waltersdorf' },
    { name: 'Bärnbach-Stadt Bezirk Voitsberg' },
    { name: 'Birkfeld' },
    { name: 'Breitenau am Hochlantsch' },
    { name: 'Bruck an der Mur-Stadt Bezirk Bruck-Mürzzuschlag' },
    { name: 'Buch-St. Magdalena ' },
    { name: 'Burgau' },
    { name: 'Dechantskirchen ' },
    { name: 'Deutsch Goritz ' },
    { name: 'Deutschfeistritz' },
    { name: 'Deutschlandsberg-Stadt Bezirk Deutschlandsberg' },
    { name: 'Dobl-Zwaring' },
    { name: 'Ebersdorf ' },
    { name: 'Edelsbach bei Feldbach ' },
    { name: 'Edelschrott' },
    { name: 'Eggersdorf bei Graz' },
    { name: 'Ehrenhausen an der Weinstraße' },
    { name: 'Eibiswald' },
    { name: 'Eichkögl ' },
    { name: 'Eisenerz-Stadt Bezirk Leoben' },
    { name: 'Empersdorf ' },
    { name: 'Fehring-Stadt Bezirk Südoststeiermark' },
    { name: 'Feistritztal ' },
    { name: 'Feldbach-Stadt Bezirk Südoststeiermark' },
    { name: 'Feldkirchen bei Graz' },
    { name: 'Fernitz-Mellach ' },
    { name: 'Fischbach ' },
    { name: 'Fladnitz an der Teichalm ' },
    { name: 'Floing ' },
    { name: 'Fohnsdorf ' },
    { name: 'Frauental an der Laßnitz' },
    { name: 'Friedberg-Stadt Bezirk Hartberg-Fürstenfeld' },
    { name: 'Frohnleiten-Stadt Bezirk Graz-Umgebung' },
    { name: 'Fürstenfeld-Stadt Bezirk Hartberg-Fürstenfeld' },
    { name: 'Gaal ' },
    { name: 'Gabersdorf ' },
    { name: 'Gaishorn am See' },
    { name: 'Gamlitz' },
    { name: 'Gasen ' },
    { name: 'Geistthal-Södingberg ' },
    { name: 'Gersdorf an der Feistritz ' },
    { name: 'Gleinstätten' },
    { name: 'Gleisdorf-Stadt Bezirk Weiz' },
    { name: 'Gnas' },
    { name: 'Gössendorf' },
    { name: 'Grafendorf bei Hartberg' },
    { name: 'Gralla' },
    { name: 'Gratkorn' },
    { name: 'Gratwein-Straßengel' },
    { name: 'Graz-Statutarstadt Bezirk Graz -Stadt)' },
    { name: 'Greinbach ' },
    { name: 'Gröbming' },
    { name: 'Groß Sankt Florian' },
    { name: 'Großklein' },
    { name: 'Großsteinbach ' },
    { name: 'Großwilfersdorf ' },
    { name: 'Grundlsee ' },
    { name: 'Gutenberg-Stenzengreith ' },
    { name: 'Halbenrain' },
    { name: 'Hart bei Graz ' },
    { name: 'Hartberg-Stadt Bezirk Hartberg-Fürstenfeld' },
    { name: 'Hartberg Umgebung ' },
    { name: 'Hartl ' },
    { name: 'Haselsdorf-Tobelbad ' },
    { name: 'Haus' },
    { name: 'Hausmannstätten' },
    { name: 'Heiligenkreuz am Waasen' },
    { name: 'Heimschuh ' },
    { name: 'Hengsberg ' },
    { name: 'Hirschegg-Pack ' },
    { name: 'Hitzendorf' },
    { name: 'Hofstätten an der Raab ' },
    { name: 'Hohentauern ' },
    { name: 'Ilz' },
    { name: 'Ilztal ' },
    { name: 'Irdning-Donnersbachtal' },
    { name: 'Jagerberg' },
    { name: 'Judenburg-Stadt Bezirk Murtal' },
    { name: 'Kainach bei Voitsberg ' },
    { name: 'Kainbach bei Graz ' },
    { name: 'Kaindorf' },
    { name: 'Kalsdorf bei Graz' },
    { name: 'Kalwang' },
    { name: 'Kammern im Liesingtal' },
    { name: 'Kapfenberg-Stadt Bezirk Bruck-Mürzzuschlag' },
    { name: 'Kapfenstein ' },
    { name: 'Kindberg-Stadt Bezirk Bruck-Mürzzuschlag' },
    { name: 'Kirchbach-Zerlach' },
    { name: 'Kirchberg an der Raab ' },
    { name: 'Kitzeck im Sausal ' },
    { name: 'Klöch' },
    { name: 'Knittelfeld-Stadt Bezirk Murtal' },
    { name: 'Kobenz' },
    { name: 'Köflach-Stadt Bezirk Voitsberg' },
    { name: 'Krakau ' },
    { name: 'Kraubath an der Mur' },
    { name: 'Krieglach' },
    { name: 'Krottendorf-Gaisfeld ' },
    { name: 'Kumberg' },
    { name: 'Lafnitz ' },
    { name: 'Landl ' },
    { name: 'Lang ' },
    { name: 'Langenwang' },
    { name: 'Lannach' },
    { name: 'Lassing ' },
    { name: 'Laßnitzhöhe' },
    { name: 'Lebring-Sankt Margarethen' },
    { name: 'Leibnitz-Stadt Bezirk Leibnitz' },
    { name: 'Leoben-Stadt Bezirk Leoben' },
    { name: 'Leutschach an der Weinstraße' },
    { name: 'Lieboch' },
    { name: 'Liezen-Stadt Bezirk Liezen' },
    { name: 'Ligist' },
    { name: 'Lobmingtal ' },
    { name: 'Ludersdorf-Wilfersdorf ' },
    { name: 'Maria Lankowitz' },
    { name: 'Mariazell-Stadt Bezirk Bruck-Mürzzuschlag' },
    { name: 'Markt Hartmannsdorf' },
    { name: 'Mautern in Steiermark' },
    { name: 'Mettersdorf am Saßbach' },
    { name: 'Michaelerberg-Pruggern ' },
    { name: 'Miesenbach bei Birkfeld ' },
    { name: 'Mitterberg-Sankt Martin ' },
    { name: 'Mitterdorf an der Raab ' },
    { name: 'Mooskirchen' },
    { name: 'Mortantsch ' },
    { name: 'Mühlen' },
    { name: 'Murau-Stadt Bezirk Murau' },
    { name: 'Mureck-Stadt Bezirk Südoststeiermark' },
    { name: 'Mürzzuschlag-Stadt Bezirk Bruck-Mürzzuschlag' },
    { name: 'Naas ' },
    { name: 'Nestelbach bei Graz ' },
    { name: 'Neuberg an der Mürz' },
    { name: 'Neudau' },
    { name: 'Neumarkt in der Steiermark' },
    { name: 'Niederwölz ' },
    { name: 'Niklasdorf' },
    { name: 'Obdach' },
    { name: 'Oberhaag ' },
    { name: 'Oberwölz-Stadt Bezirk Murau' },
    { name: 'Öblarn' },
    { name: 'Ottendorf an der Rittschein ' },
    { name: 'Paldau' },
    { name: 'Passail' },
    { name: 'Peggau' },
    { name: 'Pernegg an der Mur ' },
    { name: 'Pinggau' },
    { name: 'Pirching am Traubenberg ' },
    { name: 'Pischelsdorf am Kulm' },
    { name: 'Pölfing-Brunn' },
    { name: 'Pöllau' },
    { name: 'Pöllauberg ' },
    { name: 'Pöls-Oberkurzheim' },
    { name: 'Pölstal' },
    { name: 'Preding' },
    { name: 'Premstätten' },
    { name: 'Proleb ' },
    { name: 'Puch bei Weiz ' },
    { name: 'Pusterwald ' },
    { name: 'Raaba-Grambach' },
    { name: 'Radmer ' },
    { name: 'Ragnitz ' },
    { name: 'Ramsau am Dachstein ' },
    { name: 'Ranten ' },
    { name: 'Ratten ' },
    { name: 'Rettenegg ' },
    { name: 'Riegersburg' },
    { name: 'Rohr bei Hartberg ' },
    { name: 'Rohrbach an der Lafnitz ' },
    { name: 'Rosental an der Kainach ' },
    { name: 'Rottenmann-Stadt Bezirk Liezen' },
    { name: 'Sankt Andrä-Höch ' },
    { name: 'Sankt Anna am Aigen' },
    { name: 'Sankt Barbara im Mürztal' },
    { name: 'Sankt Bartholomä ' },
    { name: 'Sankt Gallen' },
    { name: 'Sankt Georgen am Kreischberg ' },
    { name: 'Sankt Georgen an der Stiefing' },
    { name: 'Sankt Georgen ob Judenburg ' },
    { name: 'Sankt Jakob im Walde ' },
    { name: 'Sankt Johann im Saggautal ' },
    { name: 'Sankt Johann in der Haide ' },
    { name: 'Sankt Josef (Weststeiermark) ' },
    { name: 'Sankt Kathrein am Offenegg ' },
    { name: 'Sankt Lambrecht' },
    { name: 'Sankt Lorenzen am Wechsel ' },
    { name: 'Sankt Lorenzen im Mürztal' },
    { name: 'Sankt Marein bei Graz' },
    { name: 'Sankt Marein im Mürztal' },
    { name: 'Sankt Marein-Feistritz ' },
    { name: 'Sankt Margarethen bei Knittelfeld ' },
    { name: 'Sankt Martin am Wöllmißberg ' },
    { name: 'Sankt Martin im Sulmtal ' },
    { name: 'Sankt Michael in Obersteiermark' },
    { name: 'Sankt Nikolai im Sausal' },
    { name: 'Sankt Oswald bei Plankenwarth ' },
    { name: 'Sankt Peter am Ottersbach' },
    { name: 'Sankt Peter im Sulmtal ' },
    { name: 'Sankt Peter ob Judenburg ' },
    { name: 'Sankt Peter-Freienstein' },
    { name: 'Sankt Radegund bei Graz ' },
    { name: 'Sankt Ruprecht an der Raab' },
    { name: 'Sankt Stefan im Rosental' },
    { name: 'Sankt Stefan ob Leoben ' },
    { name: 'Sankt Stefan ob Stainz ' },
    { name: 'Sankt Veit in der Südsteiermark' },
    { name: 'Schäffern ' },
    { name: 'Scheifling' },
    { name: 'Schladming-Stadt Bezirk Liezen' },
    { name: 'Schöder ' },
    { name: 'Schwarzautal' },
    { name: 'Seckau' },
    { name: 'Seiersberg-Pirka ' },
    { name: 'Selzthal ' },
    { name: 'Semriach' },
    { name: 'Sinabelkirchen' },
    { name: 'Söchau ' },
    { name: 'Söding-Sankt Johann ' },
    { name: 'Sölk ' },
    { name: 'Spielberg-Stadt Bezirk Murtal' },
    { name: 'Spital am Semmering ' },
    { name: 'St. Kathrein am Hauenstein ' },
    { name: 'St. Margarethen an der Raab' },
    { name: 'St. Peter am Kammersberg' },
    { name: 'Stadl-Predlitz ' },
    { name: 'Stainach-Pürgg' },
    { name: 'Stainz' },
    { name: 'Stallhofen' },
    { name: 'Stanz im Mürztal ' },
    { name: 'Stattegg ' },
    { name: 'Stiwoll ' },
    { name: 'Straden' },
    { name: 'Strallegg ' },
    { name: 'Straß in Steiermark' },
    { name: 'Stubenberg ' },
    { name: 'Teufenbach-Katsch ' },
    { name: 'Thal' },
    { name: 'Thannhausen ' },
    { name: 'Thörl' },
    { name: 'Tieschen' },
    { name: 'Tillmitsch ' },
    { name: 'Traboch ' },
    { name: 'Tragöß-Sankt Katharein ' },
    { name: 'Trieben-Stadt Bezirk Liezen' },
    { name: 'Trofaiach-Stadt Bezirk Leoben' },
    { name: 'Turnau' },
    { name: 'Übelbach' },
    { name: 'Unterlamm ' },
    { name: 'Unzmarkt-Frauenburg' },
    { name: 'Vasoldsberg' },
    { name: 'Voitsberg-Stadt Bezirk Voitsberg' },
    { name: 'Vorau' },
    { name: 'Vordernberg' },
    { name: 'Wagna' },
    { name: 'Wald am Schoberpaß ' },
    { name: 'Waldbach-Mönichwald ' },
    { name: 'Weinitzen ' },
    { name: 'Weißkirchen in Steiermark' },
    { name: 'Weiz-Stadt Bezirk Weiz' },
    { name: 'Wenigzell ' },
    { name: 'Werndorf ' },
    { name: 'Wettmannstätten' },
    { name: 'Wies' },
    { name: 'Wildalpen ' },
    { name: 'Wildon' },
    { name: 'Wörschach ' },
    { name: 'Wundschuh ' }
  ],

  SLB: [
    { name: 'Abtenau' },
    { name: 'Adnet' },
    { name: 'Altenmarkt im Pongau' },
    { name: 'Anif' },
    { name: 'Annaberg-Lungötz' },
    { name: 'Anthering' },
    { name: 'Bad Gastein' },
    { name: 'Bad Hofgastein' },
    { name: 'Bad Vigaun' },
    { name: 'Bergheim' },
    { name: 'Berndorf bei Salzburg' },
    { name: 'Bischofshofen-Stadt Bezirk Sankt Johann im Pongau' },
    { name: 'Bramberg am Wildkogel' },
    { name: 'Bruck an der Großglocknerstraße' },
    { name: 'Bürmoos' },
    { name: 'Dienten am Hochkönig' },
    { name: 'Dorfbeuern' },
    { name: 'Dorfgastein' },
    { name: 'Eben im Pongau' },
    { name: 'Ebenau' },
    { name: 'Elixhausen' },
    { name: 'Elsbethen' },
    { name: 'Eugendorf' },
    { name: 'Faistenau' },
    { name: 'Filzmoos' },
    { name: 'Flachau' },
    { name: 'Forstau' },
    { name: 'Fusch an der Großglocknerstraße' },
    { name: 'Fuschl am See' },
    { name: 'Goldegg' },
    { name: 'Golling an der Salzach' },
    { name: 'Göming' },
    { name: 'Göriach' },
    { name: 'Grödig' },
    { name: 'Großarl' },
    { name: 'Großgmain' },
    { name: 'Hallein-Stadt Bezirk Hallein' },
    { name: 'Hallwang' },
    { name: 'Henndorf am Wallersee' },
    { name: 'Hintersee' },
    { name: 'Hof bei Salzburg' },
    { name: 'Hollersbach im Pinzgau' },
    { name: 'Hüttau' },
    { name: 'Hüttschlag' },
    { name: 'Kaprun' },
    { name: 'Kleinarl' },
    { name: 'Koppl' },
    { name: 'Köstendorf' },
    { name: 'Krimml' },
    { name: 'Krispl' },
    { name: 'Kuchl' },
    { name: 'Lamprechtshausen' },
    { name: 'Lend' },
    { name: 'Leogang' },
    { name: 'Lessach' },
    { name: 'Lofer' },
    { name: 'Maishofen' },
    { name: 'Maria Alm am Steinernen Meer' },
    { name: 'Mariapfarr' },
    { name: 'Mattsee' },
    { name: 'Mauterndorf' },
    { name: 'Mittersill-Stadt Bezirk Zell am See' },
    { name: 'Mühlbach am Hochkönig' },
    { name: 'Muhr' },
    { name: 'Neukirchen am Großvenediger' },
    { name: 'Neumarkt am Wallersee-Stadt Bezirk Salzburg-Umgebung' },
    { name: 'Niedernsill' },
    { name: 'Nußdorf am Haunsberg' },
    { name: 'Oberalm' },
    { name: 'Oberndorf bei Salzburg-Stadt Bezirk Salzburg-Umgebung' },
    { name: 'Obertrum am See' },
    { name: 'Pfarrwerfen' },
    { name: 'Piesendorf' },
    { name: 'Plainfeld' },
    { name: 'Puch bei Hallein' },
    { name: 'Radstadt-Stadt Bezirk Sankt Johann im Pongau' },
    { name: 'Ramingstein' },
    { name: 'Rauris' },
    { name: 'Rußbach am Paß Gschütt' },
    { name: 'Saalbach-Hinterglemm' },
    { name: 'Saalfelden am Steinernen Meer-Stadt Bezirk Zell am See' },
    { name: 'Salzburg' },
    { name: 'Sankt Andrä im Lungau' },
    { name: 'Sankt Georgen bei Salzburg' },
    { name: 'Sankt Gilgen' },
    { name: 'Sankt Johann im Pongau-Stadt Bezirk Sankt Johann im Pongau' },
    { name: 'Sankt Koloman' },
    { name: 'Sankt Margarethen im Lungau' },
    { name: 'Sankt Martin am Tennengebirge' },
    { name: 'Sankt Martin bei Lofer' },
    { name: 'Sankt Michael im Lungau' },
    { name: 'Sankt Veit im Pongau' },
    { name: 'Scheffau am Tennengebirge' },
    { name: 'Schleedorf' },
    { name: 'Schwarzach im Pongau' },
    { name: 'Seeham' },
    { name: 'Seekirchen am Wallersee-Stadt Bezirk Salzburg-Umgebung' },
    { name: 'Straßwalchen' },
    { name: 'Strobl' },
    { name: 'Stuhlfelden' },
    { name: 'Tamsweg' },
    { name: 'Taxenbach' },
    { name: 'Thalgau' },
    { name: 'Thomatal' },
    { name: 'Tweng' },
    { name: 'Unken' },
    { name: 'Unternberg' },
    { name: 'Untertauern' },
    { name: 'Uttendorf' },
    { name: 'Viehhofen' },
    { name: 'Wagrain' },
    { name: 'Wald im Pinzgau' },
    { name: 'Wals-Siezenheim' },
    { name: 'Weißbach bei Lofer' },
    { name: 'Weißpriach' },
    { name: 'Werfen' },
    { name: 'Werfenweng' },
    { name: 'Zederhaus' },
    { name: 'Zell am See-Stadt Bezirk Zell am See' }
  ],

  OBOST: [
    { name: 'Adlwang' },
    { name: 'Aichkirchen' },
    { name: 'Aigen-Schlägl' },
    { name: 'Aistersheim' },
    { name: 'Alberndorf in der Riedmark' },
    { name: 'Alkoven' },
    { name: 'Allerheiligen im Mühlkreis' },
    { name: 'Allhaming' },
    { name: 'Altenberg bei Linz' },
    { name: 'Altenfelden' },
    { name: 'Altheim-Stadt Bezirk Braunau am Inn' },
    { name: 'Altmünster' },
    { name: 'Altschwendt' },
    { name: 'Ampflwang im Hausruckwald' },
    { name: 'Andorf' },
    { name: 'Andrichsfurt' },
    { name: 'Ansfelden-Stadt Bezirk Linz-Land' },
    { name: 'Antiesenhofen' },
    { name: 'Arbing' },
    { name: 'Arnreit' },
    { name: 'Aschach an der Donau' },
    { name: 'Aschach an der Steyr' },
    { name: 'Aspach' },
    { name: 'Asten' },
    { name: 'Attersee am Attersee' },
    { name: 'Attnang-Puchheim-Stadt Bezirk Vöcklabruck' },
    { name: 'Atzbach' },
    { name: 'Atzesberg' },
    { name: 'Auberg' },
    { name: 'Auerbach' },
    { name: 'Aurach am Hongar' },
    { name: 'Aurolzmünster' },
    { name: 'Bachmanning' },
    { name: 'Bad Goisern am Hallstättersee' },
    { name: 'Bad Hall-Stadt Bezirk Steyr-Land' },
    { name: 'Bad Ischl-Stadt Bezirk Gmunden' },
    { name: 'Bad Kreuzen' },
    { name: 'Bad Leonfelden-Stadt Bezirk Urfahr-Umgebung' },
    { name: 'Bad Schallerbach' },
    { name: 'Bad Wimsbach-Neydharting' },
    { name: 'Bad Zell' },
    { name: 'Baumgartenberg' },
    { name: 'Berg im Attergau' },
    { name: 'Braunau am Inn-Stadt Bezirk Braunau am Inn' },
    { name: 'Brunnenthal' },
    { name: 'Buchkirchen' },
    { name: 'Burgkirchen' },
    { name: 'Desselbrunn' },
    { name: 'Diersbach' },
    { name: 'Dietach' },
    { name: 'Dimbach' },
    { name: 'Dorf an der Pram' },
    { name: 'Ebensee am Traunsee' },
    { name: 'Eberschwang' },
    { name: 'Eberstalzell' },
    { name: 'Edlbach' },
    { name: 'Edt bei Lambach' },
    { name: 'Eferding-Stadt Bezirk Eferding' },
    { name: 'Eggelsberg' },
    { name: 'Eggendorf im Traunkreis' },
    { name: 'Eggerding' },
    { name: 'Eidenberg' },
    { name: 'Eitzing' },
    { name: 'Engelhartszell' },
    { name: 'Engerwitzdorf' },
    { name: 'Enns-Stadt Bezirk Linz-Land' },
    { name: 'Enzenkirchen' },
    { name: 'Eschenau im Hausruckkreis' },
    { name: 'Esternberg' },
    { name: 'Feldkirchen an der Donau' },
    { name: 'Feldkirchen bei Mattighofen' },
    { name: 'Fischlham' },
    { name: 'Fornach' },
    { name: 'Fraham' },
    { name: 'Frankenburg am Hausruck' },
    { name: 'Frankenmarkt' },
    { name: 'Franking' },
    { name: 'Freinberg' },
    { name: 'Freistadt-Stadt Bezirk Freistadt' },
    { name: 'Gaflenz' },
    { name: 'Gallneukirchen-Stadt Bezirk Urfahr-Umgebung' },
    { name: 'Gallspach' },
    { name: 'Gampern' },
    { name: 'Garsten' },
    { name: 'Gaspoltshofen' },
    { name: 'Geboltskirchen' },
    { name: 'Geiersberg' },
    { name: 'Geinberg' },
    { name: 'Geretsberg' },
    { name: 'Gilgenberg am Weilhart' },
    { name: 'Gmunden-Stadt Bezirk Gmunden' },
    { name: 'Goldwörth' },
    { name: 'Gosau' },
    { name: 'Gramastetten' },
    { name: 'Grein-Stadt Bezirk Perg' },
    { name: 'Grieskirchen-Stadt Bezirk Grieskirchen' },
    { name: 'Großraming' },
    { name: 'Grünau im Almtal' },
    { name: 'Grünbach' },
    { name: 'Grünburg' },
    { name: 'Gschwandt' },
    { name: 'Gunskirchen' },
    { name: 'Gurten' },
    { name: 'Gutau' },
    { name: 'Haag am Hausruck' },
    { name: 'Hagenberg im Mühlkreis' },
    { name: 'Haibach im Mühlkreis' },
    { name: 'Haibach ob der Donau' },
    { name: 'Haigermoos' },
    { name: 'Hallstatt' },
    { name: 'Handenberg' },
    { name: 'Hargelsberg' },
    { name: 'Hartkirchen' },
    { name: 'Haslach an der Mühl' },
    { name: 'Heiligenberg' },
    { name: 'Helfenberg' },
    { name: 'Hellmonsödt' },
    { name: 'Helpfau-Uttendorf' },
    { name: 'Herzogsdorf' },
    { name: 'Hinterstoder' },
    { name: 'Hinzenbach' },
    { name: 'Hirschbach im Mühlkreis' },
    { name: 'Hochburg-Ach' },
    { name: 'Hofkirchen an der Trattnach' },
    { name: 'Hofkirchen im Mühlkreis' },
    { name: 'Hofkirchen im Traunkreis' },
    { name: 'Hohenzell' },
    { name: 'Höhnhart' },
    { name: 'Holzhausen' },
    { name: 'Hörbich' },
    { name: 'Hörsching' },
    { name: 'Innerschwand am Mondsee' },
    { name: 'Inzersdorf im Kremstal' },
    { name: 'Jeging' },
    { name: 'Julbach' },
    { name: 'Kallham' },
    { name: 'Kaltenberg' },
    { name: 'Katsdorf' },
    { name: 'Kefermarkt' },
    { name: 'Kematen am Innbach' },
    { name: 'Kematen an der Krems' },
    { name: 'Kirchberg bei Mattighofen' },
    { name: 'Kirchberg ob der Donau' },
    { name: 'Kirchberg-Thening' },
    { name: 'Kirchdorf am Inn' },
    { name: 'Kirchdorf an der Krems-Stadt Bezirk Kirchdorf an der Krems' },
    { name: 'Kirchham' },
    { name: 'Kirchheim im Innkreis' },
    { name: 'Kirchschlag bei Linz' },
    { name: 'Klaffer am Hochficht' },
    { name: 'Klam' },
    { name: 'Klaus an der Pyhrnbahn' },
    { name: 'Kleinzell im Mühlkreis' },
    { name: 'Kollerschlag' },
    { name: 'Königswiesen' },
    { name: 'Kopfing im Innkreis' },
    { name: 'Kremsmünster' },
    { name: 'Krenglbach' },
    { name: 'Kronstorf' },
    { name: 'Laakirchen-Stadt Bezirk Gmunden' },
    { name: 'Lambach' },
    { name: 'Lambrechten' },
    { name: 'Langenstein' },
    { name: 'Lasberg' },
    { name: 'Laussa' },
    { name: 'Lembach im Mühlkreis' },
    { name: 'Lengau' },
    { name: 'Lenzing' },
    { name: 'Leonding-Stadt Bezirk Linz-Land' },
    { name: 'Leopoldschlag' },
    { name: 'Lichtenau im Mühlkreis' },
    { name: 'Lichtenberg' },
    { name: 'Liebenau' },
    { name: 'Linz-Bezirk Linz (Stadt)' },
    { name: 'Lochen am See' },
    { name: 'Lohnsburg am Kobernaußerwald' },
    { name: 'Losenstein' },
    { name: 'Luftenberg an der Donau' },
    { name: 'Manning' },
    { name: 'Marchtrenk-Stadt Bezirk Wels-Land' },
    { name: 'Maria Neustift' },
    { name: 'Maria Schmolln' },
    { name: 'Mattighofen-Stadt Bezirk Braunau am Inn' },
    { name: 'Mauerkirchen' },
    { name: 'Mauthausen' },
    { name: 'Mayrhof' },
    { name: 'Meggenhofen' },
    { name: 'Mehrnbach' },
    { name: 'Mettmach' },
    { name: 'Michaelnbach' },
    { name: 'Micheldorf in Oberösterreich' },
    { name: 'Mining' },
    { name: 'Mitterkirchen im Machland' },
    { name: 'Molln' },
    { name: 'Mondsee' },
    { name: 'Moosbach' },
    { name: 'Moosdorf' },
    { name: 'Mörschwang' },
    { name: 'Mühlheim am Inn' },
    { name: 'Munderfing' },
    { name: 'Münzbach' },
    { name: 'Münzkirchen' },
    { name: 'Naarn im Machlande' },
    { name: 'Natternbach' },
    { name: 'Nebelberg' },
    { name: 'Neufelden' },
    { name: 'Neuhofen an der Krems' },
    { name: 'Neuhofen im Innkreis' },
    { name: 'Neukirchen am Walde' },
    { name: 'Neukirchen an der Enknach' },
    { name: 'Neukirchen an der Vöckla' },
    { name: 'Neukirchen bei Lambach' },
    { name: 'Neumarkt im Hausruckkreis' },
    { name: 'Neumarkt im Mühlkreis' },
    { name: 'Neustift im Mühlkreis' },
    { name: 'Niederkappel' },
    { name: 'Niederneukirchen' },
    { name: 'Niederthalheim' },
    { name: 'Niederwaldkirchen' },
    { name: 'Nußbach' },
    { name: 'Nußdorf am Attersee' },
    { name: 'Oberhofen am Irrsee' },
    { name: 'Oberkappel' },
    { name: 'Obernberg am Inn' },
    { name: 'Oberndorf bei Schwanenstadt' },
    { name: 'Oberneukirchen' },
    { name: 'Oberschlierbach' },
    { name: 'Obertraun' },
    { name: 'Oberwang' },
    { name: 'Oepping' },
    { name: 'Offenhausen' },
    { name: 'Oftering' },
    { name: 'Ohlsdorf' },
    { name: 'Ort im Innkreis' },
    { name: 'Ostermiething' },
    { name: 'Ottenschlag im Mühlkreis' },
    { name: 'Ottensheim' },
    { name: 'Ottnang am Hausruck' },
    { name: 'Pabneukirchen' },
    { name: 'Palting' },
    { name: 'Pasching' },
    { name: 'Pattigham' },
    { name: 'Peilstein im Mühlviertel' },
    { name: 'Pennewang' },
    { name: 'Perg-Stadt Bezirk Perg' },
    { name: 'Perwang am Grabensee' },
    { name: 'Peterskirchen' },
    { name: 'Pettenbach' },
    { name: 'Peuerbach-Stadt Bezirk Grieskirchen' },
    { name: 'Pfaffing' },
    { name: 'Pfaffstätt' },
    { name: 'Pfarrkirchen bei Bad Hall' },
    { name: 'Pfarrkirchen im Mühlkreis' },
    { name: 'Piberbach' },
    { name: 'Pichl bei Wels' },
    { name: 'Pierbach' },
    { name: 'Pilsbach' },
    { name: 'Pinsdorf' },
    { name: 'Pischelsdorf am Engelbach' },
    { name: 'Pitzenberg' },
    { name: 'Pollham' },
    { name: 'Polling im Innkreis' },
    { name: 'Pöndorf' },
    { name: 'Pötting' },
    { name: 'Pram' },
    { name: 'Prambachkirchen' },
    { name: 'Pramet' },
    { name: 'Pregarten-Stadt Bezirk Freistadt' },
    { name: 'Puchenau' },
    { name: 'Puchkirchen am Trattberg' },
    { name: 'Pucking' },
    { name: 'Pühret' },
    { name: 'Pupping' },
    { name: 'Putzleinsdorf' },
    { name: 'Raab' },
    { name: 'Rainbach im Innkreis' },
    { name: 'Rainbach im Mühlkreis' },
    { name: 'Rechberg' },
    { name: 'Redleiten' },
    { name: 'Redlham' },
    { name: 'Regau' },
    { name: 'Reichenau im Mühlkreis' },
    { name: 'Reichenthal' },
    { name: 'Reichersberg' },
    { name: 'Reichraming' },
    { name: 'Ried im Innkreis-Stadt Bezirk Ried im Innkreis' },
    { name: 'Ried im Traunkreis' },
    { name: 'Ried in der Riedmark' },
    { name: 'Riedau' },
    { name: 'Rohr im Kremstal' },
    { name: 'Rohrbach-Berg-Stadt Bezirk Rohrbach' },
    { name: 'Roitham am Traunfall' },
    { name: 'Rosenau am Hengstpaß' },
    { name: 'Roßbach' },
    { name: 'Roßleithen' },
    { name: 'Rottenbach' },
    { name: 'Rüstorf' },
    { name: 'Rutzenham' },
    { name: 'Sandl' },
    { name: 'Sarleinsbach' },
    { name: 'Sattledt' },
    { name: 'Saxen' },
    { name: 'Schalchen' },
    { name: 'Schardenberg' },
    { name: 'Schärding-Stadt Bezirk Schärding' },
    { name: 'Scharnstein' },
    { name: 'Scharten' },
    { name: 'Schenkenfelden' },
    { name: 'Schiedlberg' },
    { name: 'Schildorn' },
    { name: 'Schlatt' },
    { name: 'Schleißheim' },
    { name: 'Schlierbach' },
    { name: 'Schlüßlberg' },
    { name: 'Schönau im Mühlkreis' },
    { name: 'Schörfling am Attersee' },
    { name: 'Schwand im Innkreis' },
    { name: 'Schwanenstadt-Stadt Bezirk Vöcklabruck' },
    { name: 'Schwarzenberg am Böhmerwald' },
    { name: 'Schwertberg' },
    { name: 'Seewalchen am Attersee' },
    { name: 'Senftenbach' },
    { name: 'Sierning' },
    { name: 'Sigharting' },
    { name: 'Sipbachzell' },
    { name: 'Sonnberg im Mühlkreis' },
    { name: 'Spital am Pyhrn' },
    { name: 'St. Aegidi' },
    { name: 'St. Agatha' },
    { name: 'St. Florian' },
    { name: 'St. Florian am Inn' },
    { name: 'St. Georgen am Fillmannsbach' },
    { name: 'St. Georgen am Walde' },
    { name: 'St. Georgen an der Gusen' },
    { name: 'St. Georgen bei Grieskirchen' },
    { name: 'St. Georgen bei Obernberg am Inn' },
    { name: 'St. Georgen im Attergau' },
    { name: 'St. Gotthard im Mühlkreis' },
    { name: 'St. Johann am Walde' },
    { name: 'St. Johann am Wimberg' },
    { name: 'St. Konrad' },
    { name: 'St. Leonhard bei Freistadt' },
    { name: 'St. Lorenz' },
    { name: 'St. Marien' },
    { name: 'St. Marienkirchen am Hausruck' },
    { name: 'St. Marienkirchen an der Polsenz' },
    { name: 'St. Marienkirchen bei Schärding' },
    { name: 'St. Martin im Innkreis' },
    { name: 'St. Martin im Mühlkreis' },
    { name: 'St. Nikola an der Donau' },
    { name: 'St. Oswald bei Freistadt' },
    { name: 'St. Oswald bei Haslach' },
    { name: 'St. Pankraz' },
    { name: 'St. Pantaleon' },
    { name: 'St. Peter am Hart' },
    { name: 'St. Peter am Wimberg' },
    { name: 'St. Radegund' },
    { name: 'St. Roman' },
    { name: 'St. Stefan-Afiesl' },
    { name: 'St. Thomas' },
    { name: 'St. Thomas am Blasenstein' },
    { name: 'St. Ulrich bei Steyr' },
    { name: 'St. Ulrich im Mühlkreis' },
    { name: 'St. Veit im Innkreis' },
    { name: 'St. Veit im Mühlkreis' },
    { name: 'St. Willibald' },
    { name: 'St. Wolfgang im Salzkammergut' },
    { name: 'Stadl-Paura' },
    { name: 'Steegen' },
    { name: 'Steinbach am Attersee' },
    { name: 'Steinbach am Ziehberg' },
    { name: 'Steinbach an der Steyr' },
    { name: 'Steinerkirchen an der Traun' },
    { name: 'Steinhaus' },
    { name: 'Steyr-Bezirk Steyr (Stadt)' },
    { name: 'Steyregg-Stadt Bezirk Urfahr-Umgebung' },
    { name: 'Straß im Attergau' },
    { name: 'Stroheim' },
    { name: 'Suben' },
    { name: 'Taiskirchen im Innkreis' },
    { name: 'Tarsdorf' },
    { name: 'Taufkirchen an der Pram' },
    { name: 'Taufkirchen an der Trattnach' },
    { name: 'Ternberg' },
    { name: 'Thalheim bei Wels' },
    { name: 'Tiefgraben' },
    { name: 'Timelkam' },
    { name: 'Tollet' },
    { name: 'Tragwein' },
    { name: 'Traun-Stadt Bezirk Linz-Land' },
    { name: 'Traunkirchen' },
    { name: 'Treubach' },
    { name: 'Tumeltsham' },
    { name: 'Überackern' },
    { name: 'Ulrichsberg' },
    { name: 'Ungenach' },
    { name: 'Unterach am Attersee' },
    { name: 'Unterweißenbach' },
    { name: 'Unterweitersdorf' },
    { name: 'Utzenaich' },
    { name: 'Vichtenstein' },
    { name: 'Vöcklabruck-Stadt Bezirk Vöcklabruck' },
    { name: 'Vöcklamarkt' },
    { name: 'Vorchdorf' },
    { name: 'Vorderstoder' },
    { name: 'Vorderweißenbach' },
    { name: 'Waizenkirchen' },
    { name: 'Waldburg' },
    { name: 'Waldhausen im Strudengau' },
    { name: 'Walding' },
    { name: 'Waldkirchen am Wesen' },
    { name: 'Waldneukirchen' },
    { name: 'Waldzell' },
    { name: 'Wallern an der Trattnach' },
    { name: 'Wartberg an der Krems' },
    { name: 'Wartberg ob der Aist' },
    { name: 'Weibern' },
    { name: 'Weilbach' },
    { name: 'Weißenkirchen im Attergau' },
    { name: 'Weißkirchen an der Traun' },
    { name: 'Weitersfelden' },
    { name: 'Wels-Bezirk Wels (Stadt)' },
    { name: 'Wendling' },
    { name: 'Weng im Innkreis' },
    { name: 'Wernstein am Inn' },
    { name: 'Weyer' },
    { name: 'Weyregg am Attersee' },
    { name: 'Wilhering' },
    { name: 'Windhaag bei Freistadt' },
    { name: 'Windhaag bei Perg' },
    { name: 'Windischgarsten' },
    { name: 'Wippenham' },
    { name: 'Wolfern' },
    { name: 'Wolfsegg am Hausruck' },
    { name: 'Zell am Moos' },
    { name: 'Zell am Pettenfirst' },
    { name: 'Zell an der Pram' },
    { name: 'Zwettl an der Rodl' }
  ],

  NDOST: [
    { name: 'Absdorf' },
    { name: 'Achau' },
    { name: 'Aderklaa' },
    { name: 'Aggsbach' },
    { name: 'Alberndorf im Pulkautal' },
    { name: 'Albrechtsberg an der Großen Krems' },
    { name: 'Alland' },
    { name: 'Allentsteig-Bezirk Zwettl' },
    { name: 'Allhartsberg' },
    { name: 'Altenburg' },
    { name: 'Altendorf' },
    { name: 'Altenmarkt an der Triesting' },
    { name: 'Altlengbach' },
    { name: 'Altlichtenwarth' },
    { name: 'Altmelon' },
    { name: 'Amaliendorf-Aalfang' },
    { name: 'Amstetten-Bezirk Amstetten' },
    { name: 'Andlersdorf' },
    { name: 'Angern an der March' },
    { name: 'Annaberg' },
    { name: 'Arbesbach' },
    { name: 'Ardagger' },
    { name: 'Artstetten-Pöbring' },
    { name: 'Aschbach-Markt' },
    { name: 'Aspangberg-St. Peter' },
    { name: 'Aspang-Markt' },
    { name: 'Asparn an der Zaya' },
    { name: 'Asperhofen' },
    { name: 'Atzenbrugg' },
    { name: 'Au am Leithaberge' },
    { name: 'Auersthal' },
    { name: 'Bad Deutsch-Altenburg' },
    { name: 'Bad Erlach' },
    { name: 'Bad Fischau-Brunn' },
    { name: 'Bad Großpertholz' },
    { name: 'Bad Pirawarth' },
    { name: 'Bad Schönau' },
    { name: 'Bad Traunstein' },
    { name: 'Bad Vöslau-Bezirk Baden' },
    { name: 'Baden-Bezirk Baden' },
    { name: 'Bärnkopf' },
    { name: 'Behamberg' },
    { name: 'Berg' },
    { name: 'Bergern im Dunkelsteinerwald' },
    { name: 'Bergland' },
    { name: 'Berndorf-Bezirk Baden' },
    { name: 'Bernhardsthal' },
    { name: 'Biberbach' },
    { name: 'Biedermannsdorf' },
    { name: 'Bisamberg' },
    { name: 'Bischofstetten' },
    { name: 'Blindenmarkt' },
    { name: 'Blumau-Neurißhof' },
    { name: 'Bockfließ' },
    { name: 'Böheimkirchen' },
    { name: 'Brand-Laaben' },
    { name: 'Brand-Nagelberg' },
    { name: 'Breitenau' },
    { name: 'Breitenfurt bei Wien' },
    { name: 'Breitenstein' },
    { name: 'Bromberg' },
    { name: 'Bruck an der Leitha-Bezirk Bruck an der Leitha' },
    { name: 'Brunn am Gebirge' },
    { name: 'Brunn an der Wild' },
    { name: 'Buchbach' },
    { name: 'Burgschleinitz-Kühnring' },
    { name: 'Bürg-Vöstenhof' },
    { name: 'Deutsch-Wagram-Bezirk Gänserndorf' },
    { name: 'Dietmanns' },
    { name: 'Dobersberg' },
    { name: 'Dorfstetten' },
    { name: 'Drasenhofen' },
    { name: 'Drosendorf-Zissersdorf-Bezirk Horn' },
    { name: 'Drösing' },
    { name: 'Droß' },
    { name: 'Dunkelsteinerwald' },
    { name: 'Dürnkrut' },
    { name: 'Dürnstein-Bezirk Krems (Land)' },
    { name: 'Ebenfurth-Bezirk Wiener Neustadt (Land)' },
    { name: 'Ebenthal' },
    { name: 'Ebergassing' },
    { name: 'Ebreichsdorf-Bezirk Baden' },
    { name: 'Echsenbach' },
    { name: 'Eckartsau' },
    { name: 'Edlitz' },
    { name: 'Eggenburg-Bezirk Horn' },
    { name: 'Eggendorf' },
    { name: 'Eggern' },
    { name: 'Eichgraben' },
    { name: 'Eisgarn' },
    { name: 'Emmersdorf an der Donau' },
    { name: 'Engelhartstetten' },
    { name: 'Ennsdorf' },
    { name: 'Enzenreith' },
    { name: 'Enzersdorf an der Fischa' },
    { name: 'Enzersfeld im Weinviertel' },
    { name: 'Enzesfeld-Lindabrunn' },
    { name: 'Erlauf' },
    { name: 'Ernstbrunn' },
    { name: 'Ernsthofen' },
    { name: 'Ertl' },
    { name: 'Eschenau' },
    { name: 'Euratsfeld' },
    { name: 'Falkenstein' },
    { name: 'Fallbach' },
    { name: 'Feistritz am Wechsel' },
    { name: 'Felixdorf' },
    { name: 'Fels am Wagram' },
    { name: 'Ferschnitz' },
    { name: 'Fischamend-Bezirk Bruck an der Leitha' },
    { name: 'Frankenfels' },
    { name: 'Furth an der Triesting' },
    { name: 'Furth bei Göttweig' },
    { name: 'Gaaden' },
    { name: 'Gablitz' },
    { name: 'Gaming' },
    { name: 'Gänserndorf-Bezirk Gänserndorf' },
    { name: 'Gars am Kamp' },
    { name: 'Gastern' },
    { name: 'Gaubitsch' },
    { name: 'Gaweinstal' },
    { name: 'Gedersdorf' },
    { name: 'Geras-Bezirk Horn' },
    { name: 'Gerasdorf bei Wien-Bezirk Korneuburg' },
    { name: 'Gerersdorf' },
    { name: 'Gföhl-Bezirk Krems (Land)' },
    { name: 'Gießhübl' },
    { name: 'Glinzendorf' },
    { name: 'Gloggnitz-Bezirk Neunkirchen' },
    { name: 'Gmünd-Bezirk Gmünd' },
    { name: 'Gnadendorf' },
    { name: 'Göllersdorf' },
    { name: 'Golling an der Erlauf' },
    { name: 'Göpfritz an der Wild' },
    { name: 'Göstling an der Ybbs' },
    { name: 'Göttlesbrunn-Arbesthal' },
    { name: 'Götzendorf an der Leitha' },
    { name: 'Grabern' },
    { name: 'Grafenbach-St. Valentin' },
    { name: 'Grafenegg' },
    { name: 'Grafenschlag' },
    { name: 'Grafenwörth' },
    { name: 'Gramatneusiedl' },
    { name: 'Gresten' },
    { name: 'Gresten-Land' },
    { name: 'Grimmenstein' },
    { name: 'Groß Gerungs-Bezirk Zwettl' },
    { name: 'Großdietmanns' },
    { name: 'Großebersdorf' },
    { name: 'Großengersdorf' },
    { name: 'Groß-Enzersdorf-Bezirk Gänserndorf' },
    { name: 'Großgöttfritz' },
    { name: 'Großharras' },
    { name: 'Großhofen' },
    { name: 'Großkrut' },
    { name: 'Großmugl' },
    { name: 'Großriedenthal' },
    { name: 'Großrußbach' },
    { name: 'Großschönau' },
    { name: 'Groß-Schweinbarth' },
    { name: 'Groß-Siegharts-Bezirk Waidhofen an der Thaya' },
    { name: 'Großweikersdorf' },
    { name: 'Grünbach am Schneeberg' },
    { name: 'Gumpoldskirchen' },
    { name: 'Günselsdorf' },
    { name: 'Guntersdorf' },
    { name: 'Guntramsdorf' },
    { name: 'Gutenbrunn' },
    { name: 'Gutenstein' },
    { name: 'Haag-Bezirk Amstetten' },
    { name: 'Hadersdorf-Kammern' },
    { name: 'Hadres' },
    { name: 'Hafnerbach' },
    { name: 'Hagenbrunn' },
    { name: 'Haidershofen' },
    { name: 'Hainburg a.d. Donau-Bezirk Bruck an der Leitha' },
    { name: 'Hainfeld-Bezirk Lilienfeld' },
    { name: 'Hardegg-Bezirk Hollabrunn' },
    { name: 'Haringsee' },
    { name: 'Harmannsdorf' },
    { name: 'Haslau-Maria Ellend' },
    { name: 'Haugschlag' },
    { name: 'Haugsdorf' },
    { name: 'Haunoldstein' },
    { name: 'Hausbrunn' },
    { name: 'Hauskirchen' },
    { name: 'Hausleiten' },
    { name: 'Heidenreichstein-Bezirk Gmünd' },
    { name: 'Heiligenkreuz' },
    { name: 'Heldenberg' },
    { name: 'Hennersdorf' },
    { name: 'Hernstein' },
    { name: 'Herrnbaumgarten' },
    { name: 'Herzogenburg-Bezirk Sankt Pölten (Land)' },
    { name: 'Himberg' },
    { name: 'Hinterbrühl' },
    { name: 'Hirschbach' },
    { name: 'Hirtenberg' },
    { name: 'Hochleithen' },
    { name: 'Hochneukirchen-Gschaidt' },
    { name: 'Hochwolkersdorf' },
    { name: 'Hof am Leithaberge' },
    { name: 'Hofamt Priel' },
    { name: 'Höflein' },
    { name: 'Höflein an der Hohen Wand' },
    { name: 'Hofstetten-Grünau' },
    { name: 'Hohe Wand' },
    { name: 'Hohenau an der March' },
    { name: 'Hohenberg' },
    { name: 'Hoheneich' },
    { name: 'Hohenruppersdorf' },
    { name: 'Hohenwarth-Mühlbach a.M.' },
    { name: 'Hollabrunn-Bezirk Hollabrunn' },
    { name: 'Hollenstein an der Ybbs' },
    { name: 'Hollenthon' },
    { name: 'Horn-Bezirk Horn' },
    { name: 'Hundsheim' },
    { name: 'Hürm' },
    { name: 'Inzersdorf-Getzersdorf' },
    { name: 'Irnfritz-Messern' },
    { name: 'Jaidhof' },
    { name: 'Japons' },
    { name: 'Jedenspeigen' },
    { name: 'Judenau-Baumgarten' },
    { name: 'Kaltenleutgeben' },
    { name: 'Kapelln' },
    { name: 'Karlstein an der Thaya' },
    { name: 'Karlstetten' },
    { name: 'Kasten bei Böheimkirchen' },
    { name: 'Katzelsdorf' },
    { name: 'Kaumberg' },
    { name: 'Kautzen' },
    { name: 'Kematen an der Ybbs' },
    { name: 'Kilb' },
    { name: 'Kirchberg am Wagram' },
    { name: 'Kirchberg am Walde' },
    { name: 'Kirchberg am Wechsel' },
    { name: 'Kirchberg an der Pielach' },
    { name: 'Kirchschlag' },
    { name: 'Kirchschlag in der Buckligen Welt-Bezirk Wiener Neustadt (Land)' },
    { name: 'Kirchstetten' },
    { name: 'Kirnberg an der Mank' },
    { name: 'Klausen-Leopoldsdorf' },
    { name: 'Klein-Neusiedl' },
    { name: 'Klein-Pöchlarn' },
    { name: 'Kleinzell' },
    { name: 'Klosterneuburg-Bezirk Tulln' },
    { name: 'Königsbrunn am Wagram' },
    { name: 'Königstetten' },
    { name: 'Korneuburg-Bezirk Korneuburg' },
    { name: 'Kottes-Purk' },
    { name: 'Kottingbrunn' },
    { name: 'Krems an der Donau-Bezirk Krems an der Donau' },
    { name: 'Kreuttal' },
    { name: 'Kreuzstetten' },
    { name: 'Krumau am Kamp' },
    { name: 'Krumbach' },
    { name: 'Krummnußbaum' },
    { name: 'Laa an der Thaya-Bezirk Mistelbach' },
    { name: 'Laab im Walde' },
    { name: 'Ladendorf' },
    { name: 'Langau' },
    { name: 'Langenlois-Bezirk Krems (Land)' },
    { name: 'Langenrohr' },
    { name: 'Langenzersdorf' },
    { name: 'Langschlag' },
    { name: 'Lanzendorf' },
    { name: 'Lanzenkirchen' },
    { name: 'Lassee' },
    { name: 'Laxenburg' },
    { name: 'Leiben' },
    { name: 'Leitzersdorf' },
    { name: 'Lengenfeld' },
    { name: 'Leobendorf' },
    { name: 'Leobersdorf' },
    { name: 'Leopoldsdorf' },
    { name: 'Leopoldsdorf im Marchfeld' },
    { name: 'Lichtenau im Waldviertel' },
    { name: 'Lichtenegg' },
    { name: 'Lichtenwörth' },
    { name: 'Lilienfeld-Bezirk Lilienfeld' },
    { name: 'Litschau-Bezirk Gmünd' },
    { name: 'Loich' },
    { name: 'Loosdorf' },
    { name: 'Ludweis-Aigen' },
    { name: 'Lunz am See' },
    { name: 'Mailberg' },
    { name: 'Maissau-Bezirk Hollabrunn' },
    { name: 'Mank-Bezirk Melk' },
    { name: 'Mannersdorf am Leithagebirge-Bezirk Bruck an der Leitha' },
    { name: 'Mannsdorf an der Donau' },
    { name: 'Marbach an der Donau' },
    { name: 'Marchegg-Bezirk Gänserndorf' },
    { name: 'Maria Enzersdorf' },
    { name: 'Maria Laach am Jauerling' },
    { name: 'Maria Taferl' },
    { name: 'Maria-Anzbach' },
    { name: 'Maria-Lanzendorf' },
    { name: 'Markersdorf-Haindorf' },
    { name: 'Markgrafneusiedl' },
    { name: 'Markt Piesting' },
    { name: 'Martinsberg' },
    { name: 'Matzendorf-Hölles' },
    { name: 'Matzen-Raggendorf' },
    { name: 'Mauerbach' },
    { name: 'Mautern an der Donau-Bezirk Krems (Land)' },
    { name: 'Meiseldorf' },
    { name: 'Melk-Bezirk Melk' },
    { name: 'Michelbach' },
    { name: 'Michelhausen' },
    { name: 'Miesenbach' },
    { name: 'Mistelbach-Bezirk Mistelbach' },
    { name: 'Mitterbach am Erlaufsee' },
    { name: 'Mitterndorf an der Fischa' },
    { name: 'Mödling-Bezirk Mödling' },
    { name: 'Mönichkirchen' },
    { name: 'Moorbad Harbach' },
    { name: 'Moosbrunn' },
    { name: 'Muckendorf-Wipfing' },
    { name: 'Muggendorf' },
    { name: 'Mühldorf' },
    { name: 'Münchendorf' },
    { name: 'Münichreith-Laimbach' },
    { name: 'Nappersdorf-Kammersdorf' },
    { name: 'Natschbach-Loipersbach' },
    { name: 'Neidling' },
    { name: 'Neudorf im Weinviertel' },
    { name: 'Neuhofen an der Ybbs' },
    { name: 'Neulengbach-Bezirk Sankt Pölten (Land)' },
    { name: 'Neumarkt an der Ybbs' },
    { name: 'Neunkirchen-Bezirk Neunkirchen' },
    { name: 'Neusiedl an der Zaya' },
    { name: 'Neustadtl an der Donau' },
    { name: 'Neustift-Innermanzing' },
    { name: 'Niederhollabrunn' },
    { name: 'Niederleis' },
    { name: 'Nöchling' },
    { name: 'Nußdorf ob der Traisen' },
    { name: 'Ober-Grafendorf' },
    { name: 'Oberndorf an der Melk' },
    { name: 'Obersiebenbrunn' },
    { name: 'Oberwaltersdorf' },
    { name: 'Obritzberg-Rust' },
    { name: 'Oed-Oehling' },
    { name: 'Opponitz' },
    { name: 'Orth an der Donau' },
    { name: 'Ottenschlag' },
    { name: 'Ottenthal' },
    { name: 'Otterthal' },
    { name: 'Palterndorf-Dobermannsdorf' },
    { name: 'Parbasdorf' },
    { name: 'Paudorf' },
    { name: 'Payerbach' },
    { name: 'Perchtoldsdorf' },
    { name: 'Pernegg' },
    { name: 'Pernersdorf' },
    { name: 'Pernitz' },
    { name: 'Perschling' },
    { name: 'Persenbeug-Gottsdorf' },
    { name: 'Petronell-Carnuntum' },
    { name: 'Petzenkirchen' },
    { name: 'Pfaffenschlag bei Waidhofen a.d.Thaya' },
    { name: 'Pfaffstätten' },
    { name: 'Pillichsdorf' },
    { name: 'Pitten' },
    { name: 'Pöchlarn-Bezirk Melk' },
    { name: 'Pöggstall' },
    { name: 'Pölla' },
    { name: 'Pottendorf' },
    { name: 'Pottenstein' },
    { name: 'Poysdorf-Bezirk Mistelbach' },
    { name: 'Prellenkirchen' },
    { name: 'Pressbaum-Bezirk Sankt Pölten (Land)' },
    { name: 'Prigglitz' },
    { name: 'Prinzersdorf' },
    { name: 'Prottes' },
    { name: 'Puchberg am Schneeberg' },
    { name: 'Puchenstuben' },
    { name: 'Pulkau-Bezirk Hollabrunn' },
    { name: 'Purgstall an der Erlauf' },
    { name: 'Purkersdorf-Bezirk Sankt Pölten (Land)' },
    { name: 'Pyhra' },
    { name: 'Raabs an der Thaya-Bezirk Waidhofen an der Thaya' },
    { name: 'Raach am Hochgebirge' },
    { name: 'Raasdorf' },
    { name: 'Rabensburg' },
    { name: 'Rabenstein an der Pielach' },
    { name: 'Ramsau' },
    { name: 'Randegg' },
    { name: 'Rappottenstein' },
    { name: 'Rastenfeld' },
    { name: 'Rauchenwarth' },
    { name: 'Ravelsbach' },
    { name: 'Raxendorf' },
    { name: 'Reichenau an der Rax' },
    { name: 'Reingers' },
    { name: 'Reinsberg' },
    { name: 'Reisenberg' },
    { name: 'Retz-Bezirk Hollabrunn' },
    { name: 'Retzbach' },
    { name: 'Ringelsdorf-Niederabsdorf' },
    { name: 'Rohr im Gebirge' },
    { name: 'Rohrau' },
    { name: 'Rohrbach an der Gölsen' },
    { name: 'Röhrenbach' },
    { name: 'Rohrendorf bei Krems' },
    { name: 'Röschitz' },
    { name: 'Rosenburg-Mold' },
    { name: 'Rossatz-Arnsdorf' },
    { name: 'Ruprechtshofen' },
    { name: 'Rußbach' },
    { name: 'Sallingberg' },
    { name: 'Scharndorf' },
    { name: 'Scheibbs-Bezirk Scheibbs' },
    { name: 'Scheiblingkirchen-Thernberg' },
    { name: 'Schollach' },
    { name: 'Schönau an der Triesting' },
    { name: 'Schönbach' },
    { name: 'Schönberg am Kamp' },
    { name: 'Schönbühel-Aggsbach' },
    { name: 'Schönkirchen-Reyersdorf' },
    { name: 'Schottwien' },
    { name: 'Schrattenbach' },
    { name: 'Schrattenberg' },
    { name: 'Schrattenthal-Bezirk Hollabrunn' },
    { name: 'Schrems-Bezirk Gmünd' },
    { name: 'Schwadorf' },
    { name: 'Schwarzau am Steinfeld' },
    { name: 'Schwarzau im Gebirge' },
    { name: 'Schwarzenau' },
    { name: 'Schwarzenbach' },
    { name: 'Schwarzenbach an der Pielach' },
    { name: 'Schwechat-Bezirk Bruck an der Leitha' },
    { name: 'Schweiggers' },
    { name: 'Seebenstein' },
    { name: 'Seefeld-Kadolz' },
    { name: 'Seibersdorf' },
    { name: 'Seitenstetten' },
    { name: 'Semmering' },
    { name: 'Senftenberg' },
    { name: 'Sieghartskirchen' },
    { name: 'Sierndorf' },
    { name: 'Sigmundsherberg' },
    { name: 'Sitzenberg-Reidling' },
    { name: 'Sitzendorf an der Schmida' },
    { name: 'Sollenau' },
    { name: 'Sommerein' },
    { name: 'Sonntagberg' },
    { name: 'Sooß' },
    { name: 'Spannberg' },
    { name: 'Spillern' },
    { name: 'Spitz' },
    { name: 'St. Aegyd am Neuwalde' },
    { name: 'St. Andrä-Wördern' },
    { name: 'St. Anton an der Jeßnitz' },
    { name: 'St. Bernhard-Frauenhofen' },
    { name: 'St. Corona am Wechsel' },
    { name: 'St. Egyden am Steinfeld' },
    { name: 'St. Georgen am Reith' },
    { name: 'St. Georgen am Ybbsfelde' },
    { name: 'St. Georgen an der Leys' },
    { name: 'St. Leonhard am Forst' },
    { name: 'St. Leonhard am Hornerwald' },
    { name: 'St. Margarethen an der Sierning' },
    { name: 'St. Martin' },
    { name: 'St. Martin-Karlsbach' },
    { name: 'St. Oswald' },
    { name: 'St. Pantaleon-Erla' },
    { name: 'St. Peter in der Au' },
    { name: 'St. Pölten-Bezirk Sankt Pölten (Stadt)' },
    { name: 'St. Valentin-Bezirk Amstetten' },
    { name: 'St. Veit an der Gölsen' },
    { name: 'Staatz' },
    { name: 'Statzendorf' },
    { name: 'Steinakirchen am Forst' },
    { name: 'Stetteldorf am Wagram' },
    { name: 'Stetten' },
    { name: 'Stockerau-Bezirk Korneuburg' },
    { name: 'Stössing' },
    { name: 'Straning-Grafenberg' },
    { name: 'Straß im Straßertale' },
    { name: 'Strasshof an der Nordbahn' },
    { name: 'Stratzing' },
    { name: 'Strengberg' },
    { name: 'Stronsdorf' },
    { name: 'Sulz im Weinviertel' },
    { name: 'Tattendorf' },
    { name: 'Teesdorf' },
    { name: 'Ternitz-Bezirk Neunkirchen' },
    { name: 'Texingtal' },
    { name: 'Thaya' },
    { name: 'Theresienfeld' },
    { name: 'Thomasberg' },
    { name: 'Traisen' },
    { name: 'Traiskirchen-Bezirk Baden' },
    { name: 'Traismauer-Bezirk Sankt Pölten (Land)' },
    { name: 'Trattenbach' },
    { name: 'Trautmannsdorf an der Leitha' },
    { name: 'Trumau' },
    { name: 'Tulbing' },
    { name: 'Tulln an der Donau-Bezirk Tulln' },
    { name: 'Tullnerbach' },
    { name: 'Türnitz' },
    { name: 'Ulrichskirchen-Schleinbach' },
    { name: 'Unserfrau-Altweitra' },
    { name: 'Untersiebenbrunn' },
    { name: 'Unterstinkenbrunn' },
    { name: 'Velm-Götzendorf' },
    { name: 'Viehdorf' },
    { name: 'Vitis' },
    { name: 'Vösendorf' },
    { name: 'Waidhofen an der Thaya-Bezirk Waidhofen an der Thaya' },
    { name: 'Waidhofen an der Thaya-Land' },
    { name: 'Waidhofen an der Ybbs-Bezirk Waidhofen an der Ybbs (Stadt)' },
    { name: 'Waidmannsfeld' },
    { name: 'Waldegg' },
    { name: 'Waldenstein' },
    { name: 'Waldhausen' },
    { name: 'Waldkirchen an der Thaya' },
    { name: 'Wallsee-Sindelburg' },
    { name: 'Walpersbach' },
    { name: 'Wang' },
    { name: 'Warth' },
    { name: 'Wartmannstetten' },
    { name: 'Weiden an der March' },
    { name: 'Weikendorf' },
    { name: 'Weikersdorf am Steinfelde' },
    { name: 'Weinburg' },
    { name: 'Weinzierl am Walde' },
    { name: 'Weissenbach an der Triesting' },
    { name: 'Weißenkirchen in der Wachau' },
    { name: 'Weistrach' },
    { name: 'Weiten' },
    { name: 'Weitersfeld' },
    { name: 'Weitra-Bezirk Gmünd' },
    { name: 'Wiener Neudorf' },
    { name: 'Wiener Neustadt-Bezirk Wiener Neustadt (Stadt)' },
    { name: 'Wienerwald' },
    { name: 'Wieselburg-Bezirk Scheibbs' },
    { name: 'Wieselburg-Land' },
    { name: 'Wiesmath' },
    { name: 'Wildendürnbach' },
    { name: 'Wilfersdorf' },
    { name: 'Wilhelmsburg-Bezirk Sankt Pölten (Land)' },
    { name: 'Willendorf' },
    { name: 'Wimpassing im Schwarzatale' },
    { name: 'Windigsteig' },
    { name: 'Winklarn' },
    { name: 'Winzendorf-Muthmannsdorf' },
    { name: 'Wölbling' },
    { name: 'Wolfpassing' },
    { name: 'Wolfsbach' },
    { name: 'Wolfsgraben' },
    { name: 'Wolfsthal' },
    { name: 'Wolkersdorf im Weinviertel-Bezirk Mistelbach' },
    { name: 'Wöllersdorf-Steinabrückl' },
    { name: 'Wullersdorf' },
    { name: 'Würflach' },
    { name: 'Würmla' },
    { name: 'Ybbs an der Donau-Bezirk Melk' },
    { name: 'Ybbsitz' },
    { name: 'Yspertal' },
    { name: 'Zeillern' },
    { name: 'Zeiselmauer-Wolfpassing' },
    { name: 'Zelking-Matzleinsdorf' },
    { name: 'Zellerndorf' },
    { name: 'Ziersdorf' },
    { name: 'Zillingdorf' },
    { name: 'Zistersdorf-Bezirk Gänserndorf' },
    { name: 'Zöbern' },
    { name: 'Zwentendorf an der Donau' },
    { name: 'Zwettl-Niederösterreich-Bezirk Zwettl' },
    { name: 'Zwölfaxing' }
  ],

  KRTN: [
    
      { name: 'Afritz am See' },
      { name: 'Albeck' },
      { name: 'Althofen-Stadt Bezirk Sankt Veit an der Glan' },
      { name: 'Arnoldstein' },
      { name: 'Arriach' },
      { name: 'Bad Bleiberg' },
      { name: 'Bad Kleinkirchheim' },
      { name: 'Bad St. Leonhard im Lavanttal-Stadt Bezirk Wolfsberg' },
      { name: 'Baldramsdorf' },
      { name: 'Berg im Drautal' },
      { name: 'Bleiburg-Stadt Bezirk Völkermarkt' },
      { name: 'Brückl' },
      { name: 'Dellach' },
      { name: 'Dellach im Drautal' },
      { name: 'Deutsch-Griffen' },
      { name: 'Diex' },
      { name: 'Ebenthal in Kärnten' },
      { name: 'Eberndorf' },
      { name: 'Eberstein' },
      { name: 'Eisenkappel-Vellach' },
      { name: 'Feistritz an der Gail' },
      { name: 'Feistritz im Rosental' },
      { name: 'Feistritz ob Bleiburg' },
      { name: 'Feld am See' },
      { name: 'Feldkirchen in Kärnten-Stadt Bezirk Feldkirchen' },
      { name: 'Ferlach-Stadt Bezirk Klagenfurt Land' },
      { name: 'Ferndorf' },
      { name: 'Finkenstein am Faaker See' },
      { name: 'Flattach' },
      { name: 'Frantschach-St. Gertraud' },
      { name: 'Frauenstein' },
      { name: 'Fresach' },
      { name: 'Friesach-Stadt Bezirk Sankt Veit an der Glan' },
      { name: 'Gallizien' },
      { name: 'Gitschtal' },
      { name: 'Glanegg' },
      { name: 'Globasnitz' },
      { name: 'Glödnitz' },
      { name: 'Gmünd in Kärnten-Stadt Bezirk Spittal an der Drau' },
      { name: 'Gnesau' },
      { name: 'Grafenstein' },
      { name: 'Greifenburg' },
      { name: 'Griffen' },
      { name: 'Großkirchheim' },
      { name: 'Gurk' },
      { name: 'Guttaring' },
      { name: 'Heiligenblut am Großglockner' },
      { name: 'Hermagor-Pressegger See-Stadt Bezirk Hermagor' },
      { name: 'Himmelberg' },
      { name: 'Hohenthurn' },
      { name: 'Hüttenberg' },
      { name: 'Irschen' },
      { name: 'Kappel am Krappfeld' },
      { name: 'Keutschach am See' },
      { name: 'Kirchbach' },
      { name: 'Klagenfurt am Wörthersee-Bezirk Klagenfurt (Stadt)' },
      { name: 'Kleblach-Lind' },
      { name: 'Klein St. Paul' },
      { name: 'Kötschach-Mauthen' },
      { name: 'Köttmannsdorf' },
      { name: 'Krems in Kärnten' },
      { name: 'Krumpendorf am Wörthersee' },
      { name: 'Lavamünd' },
      { name: 'Lendorf' },
      { name: 'Lesachtal' },
      { name: 'Liebenfels' },
      { name: 'Ludmannsdorf' },
      { name: 'Lurnfeld' },
      { name: 'Magdalensberg' },
      { name: 'Mallnitz' },
      { name: 'Malta' },
      { name: 'Maria Rain' },
      { name: 'Maria Saal' },
      { name: 'Maria Wörth' },
      { name: 'Metnitz' },
      { name: 'Micheldorf' },
      { name: 'Millstatt am See' },
      { name: 'Mölbling' },
      { name: 'Moosburg' },
      { name: 'Mörtschach' },
      { name: 'Mühldorf' },
      { name: 'Neuhaus' },
      { name: 'Nötsch im Gailtal' },
      { name: 'Oberdrauburg' },
      { name: 'Obervellach' },
      { name: 'Ossiach' },
      { name: 'Paternion' },
      { name: 'Poggersdorf' },
      { name: 'Pörtschach am Wörther See' },
      { name: 'Preitenegg' },
      { name: 'Radenthein-Stadt Bezirk Spittal an der Drau' },
      { name: 'Rangersdorf' },
      { name: 'Reichenau' },
      { name: 'Reichenfels' },
      { name: 'Reißeck' },
      { name: 'Rennweg am Katschberg' },
      { name: 'Rosegg' },
      { name: 'Ruden' },
      { name: 'Sachsenburg' },
      { name: 'Schiefling am Wörthersee' },
      { name: 'Seeboden am Millstätter See' },
      { name: 'Sittersdorf' },
      { name: 'Spittal an der Drau-Stadt Bezirk Spittal an der Drau' },
      { name: 'St. Andrä-Stadt Bezirk Wolfsberg' },
      { name: 'St. Georgen am Längsee' },
      { name: 'St. Georgen im Lavanttal' },
      { name: 'St. Jakob im Rosental' },
      { name: 'St. Kanzian am Klopeiner See' },
      { name: 'St. Margareten im Rosental' },
      { name: 'St. Paul im Lavanttal' },
      { name: 'St. Stefan im Gailtal' },
      { name: 'St. Urban' },
      { name: 'St. Veit an der Glan-Stadt Bezirk Sankt Veit an der Glan' },
      { name: 'Stall' },
      { name: 'Steindorf am Ossiacher See' },
      { name: 'Steinfeld' },
      { name: 'Steuerberg' },
      { name: 'Stockenboi' },
      { name: 'Straßburg-Stadt Bezirk Sankt Veit an der Glan' },
      { name: 'Techelsberg am Wörther See' },
      { name: 'Trebesing' },
      { name: 'Treffen am Ossiacher See' },
      { name: 'Velden am Wörther See' },
      { name: 'Villach-Bezirk Villach (Stadt)' },
      { name: 'Völkermarkt-Stadt Bezirk Völkermarkt' },
      { name: 'Weißensee' },
      { name: 'Weißenstein' },
      { name: 'Weitensfeld im Gurktal' },
      { name: 'Wernberg' },
      { name: 'Winklern' },
      { name: 'Wolfsberg-Stadt Bezirk Wolfsberg' },
      { name: 'Zell' }
    
  ],

  BRGL: [
    { name: 'Andau' },
    { name: 'Antau' },
    { name: 'Apetlon' },
    { name: 'Bad Sauerbrunn' },
    { name: 'Bad Tatzmannsdorf' },
    { name: 'Badersdorf' },
    { name: 'Baumgarten' },
    { name: 'Bernstein' },
    { name: 'Bildein' },
    { name: 'Bocksdorf' },
    { name: 'Breitenbrunn am Neusiedler See' },
    { name: 'Bruckneudorf' },
    { name: 'Burgauberg-Neudauberg' },
    { name: 'Deutsch Jahrndorf' },
    { name: 'Deutsch Kaltenbrunn' },
    { name: 'Deutsch Schützen-Eisenberg' },
    { name: 'Deutschkreutz' },
    { name: 'Donnerskirchen' },
    { name: 'Draßburg' },
    { name: 'Draßmarkt' },
    { name: 'Eberau' },
    { name: 'Edelstal' },
    { name: 'Eisenstadt-Bezirk Eisenstadt (Stadt)' },
    { name: 'Eltendorf' },
    { name: 'Forchtenstein' },
    { name: 'Frankenau-Unterpullendorf' },
    { name: 'Frauenkirchen-Bezirk Neusiedl am See' },
    { name: 'Gattendorf' },
    { name: 'Gerersdorf-Sulz' },
    { name: 'Gols' },
    { name: 'Grafenschachen' },
    { name: 'Großhöflein' },
    { name: 'Großmürbisch' },
    { name: 'Großpetersdorf' },
    { name: 'Großwarasdorf' },
    { name: 'Güssing-Bezirk Güssing' },
    { name: 'Güttenbach' },
    { name: 'Hackerberg' },
    { name: 'Halbturn' },
    { name: 'Hannersdorf' },
    { name: 'Heiligenbrunn' },
    { name: 'Heiligenkreuz im Lafnitztal' },
    { name: 'Heugraben' },
    { name: 'Hirm' },
    { name: 'Horitschon' },
    { name: 'Hornstein' },
    { name: 'Illmitz' },
    { name: 'Inzenhof' },
    { name: 'Jabing' },
    { name: 'Jennersdorf-Bezirk Jennersdorf' },
    { name: 'Jois' },
    { name: 'Kaisersdorf' },
    { name: 'Kemeten' },
    { name: 'Kittsee' },
    { name: 'Kleinmürbisch' },
    { name: 'Klingenbach' },
    { name: 'Kobersdorf' },
    { name: 'Kohfidisch' },
    { name: 'Königsdorf' },
    { name: 'Krensdorf' },
    { name: 'Kukmirn' },
    { name: 'Lackenbach' },
    { name: 'Lackendorf' },
    { name: 'Leithaprodersdorf' },
    { name: 'Litzelsdorf' },
    { name: 'Lockenhaus' },
    { name: 'Loipersbach im Burgenland' },
    { name: 'Loipersdorf-Kitzladen' },
    { name: 'Loretto' },
    { name: 'Lutzmannsburg' },
    { name: 'Mannersdorf an der Rabnitz' },
    { name: 'Mariasdorf' },
    { name: 'Markt Allhau' },
    { name: 'Markt Neuhodis' },
    { name: 'Markt Sankt Martin' },
    { name: 'Marz' },
    { name: 'Mattersburg-Bezirk Mattersburg' },
    { name: 'Minihof-Liebau' },
    { name: 'Mischendorf' },
    { name: 'Mogersdorf' },
    { name: 'Mönchhof' },
    { name: 'Mörbisch am See' },
    { name: 'Moschendorf' },
    { name: 'Mühlgraben' },
    { name: 'Müllendorf' },
    { name: 'Neckenmarkt' },
    { name: 'Neuberg im Burgenland' },
    { name: 'Neudorf' },
    { name: 'Neudörfl' },
    { name: 'Neufeld an der Leitha-Bezirk Eisenstadt-Umgebung' },
    { name: 'Neuhaus am Klausenbach' },
    { name: 'Neusiedl am See-Bezirk Neusiedl am See' },
    { name: 'Neustift an der Lafnitz' },
    { name: 'Neustift bei Güssing' },
    { name: 'Neutal' },
    { name: 'Nickelsdorf' },
    { name: 'Nikitsch' },
    { name: 'Oberdorf im Burgenland' },
    { name: 'Oberloisdorf' },
    { name: 'Oberpullendorf-Bezirk Oberpullendorf' },
    { name: 'Oberschützen' },
    { name: 'Oberwart-Bezirk Oberwart' },
    { name: 'Oggau am Neusiedler See' },
    { name: 'Olbendorf' },
    { name: 'Ollersdorf im Burgenland' },
    { name: 'Oslip' },
    { name: 'Pama' },
    { name: 'Pamhagen' },
    { name: 'Parndorf' },
    { name: 'Pilgersdorf' },
    { name: 'Pinkafeld-Bezirk Oberwart' },
    { name: 'Piringsdorf' },
    { name: 'Podersdorf am See' },
    { name: 'Pöttelsdorf' },
    { name: 'Pöttsching' },
    { name: 'Potzneusiedl' },
    { name: 'Purbach am Neusiedler See-Bezirk Eisenstadt-Umgebung' },
    { name: 'Raiding' },
    { name: 'Rauchwart' },
    { name: 'Rechnitz' },
    { name: 'Riedlingsdorf' },
    { name: 'Ritzing' },
    { name: 'Rohr im Burgenland' },
    { name: 'Rohrbach bei Mattersburg' },
    { name: 'Rotenturm an der Pinka' },
    { name: 'Rudersdorf' },
    { name: 'Rust-Bezirk Rust (Stadt)' },
    { name: 'Sankt Andrä am Zicksee' },
    { name: 'Sankt Margarethen im Burgenland' },
    { name: 'Sankt Martin an der Raab' },
    { name: 'Sankt Michael im Burgenland' },
    { name: 'Schachendorf' },
    { name: 'Schandorf' },
    { name: 'Schattendorf' },
    { name: 'Schützen am Gebirge' },
    { name: 'Siegendorf' },
    { name: 'Sieggraben' },
    { name: 'Sigleß' },
    { name: 'Stadtschlaining-Bezirk Oberwart' },
    { name: 'Stegersbach' },
    { name: 'Steinberg-Dörfl' },
    { name: 'Steinbrunn' },
    { name: 'Stinatz' },
    { name: 'Stoob' },
    { name: 'Stotzing' },
    { name: 'Strem' },
    { name: 'Tadten' },
    { name: 'Tobaj' },
    { name: 'Trausdorf an der Wulka' },
    { name: 'Tschanigraben' },
    { name: 'Unterfrauenhaid' },
    { name: 'Unterkohlstätten' },
    { name: 'Unterrabnitz-Schwendgraben' },
    { name: 'Unterwart' },
    { name: 'Wallern im Burgenland' },
    { name: 'Weichselbaum' },
    { name: 'Weiden am See' },
    { name: 'Weiden bei Rechnitz' },
    { name: 'Weingraben' },
    { name: 'Weppersdorf' },
    { name: 'Wiesen' },
    { name: 'Wiesfleck' },
    { name: 'Wimpassing an der Leitha' },
    { name: 'Winden am See' },
    { name: 'Wolfau' },
    { name: 'Wörterberg' },
    { name: 'Wulkaprodersdorf' },
    { name: 'Zagersdorf' },
    { name: 'Zemendorf-Stöttera' },
    { name: 'Zillingtal' },
    { name: 'Zurndorf' }
  ]
};
